### ISSUE TITLE
Mod breaks on 1.31.1

### ISSUE THREAD

**Issue by WentTheFox** [DJDavid98/DiscordCore#1]
Imported from DJDavid98/bsrpc#8

CC @AltEvolutions

**Comment by WentTheFox** [comment]
I created release v3.0.2 built for game version 1.31.1, @AltEvolutions please check if this release works for you.

**Comment by AltEvolutions** [comment]
Can confirm that DiscordCore now seems to completely work, but now the main BSRPC.dll is throwing an error which seems to be the exact same error that DiscordCore displayed

```
[DEBUG @ 17:05:52 | bsrpc] bsrpcController: Awake()
[ERROR @ 17:05:52 | IPA] bsrpc OnEnable: System.TypeLoadException: Could not resolve type with token 0100002e from typeref (expected class 'PersistentSingleton`1' in assembly 'HMLib, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null')
[ERROR @ 17:05:52 | IPA]   at bsrpc.Plugin.OnApplicationStart () [0x0003c] in D:\Git\bsrpc\Plugin.cs:42 
[ERROR @ 17:05:52 | IPA]   at (wrapper dynamic-method) System.Object.lambda_method(System.Runtime.CompilerServices.Closure,object)
[ERROR @ 17:05:52 | IPA]   at IPA.Loader.PluginExecutor.Enable () [0x00000] in D:\a\BeatSaber-IPA-Reloaded\BeatSaber-IPA-Reloaded\IPA.Loader\Loader\PluginExecutor.cs:61 
[ERROR @ 17:05:52 | IPA]   at IPA.Loader.Composite.CompositeBSPlugin+<>c.<OnEnable>b__4_0 (IPA.Loader.PluginExecutor plugin) [0x00000] in D:\a\BeatSaber-IPA-Reloaded\BeatSaber-IPA-Reloaded\IPA.Loader\Loader\Composite\CompositeBSPlugin.cs:36 
[ERROR @ 17:05:52 | IPA]   at IPA.Loader.Composite.CompositeBSPlugin.Invoke (IPA.Loader.Composite.CompositeBSPlugin+CompositeCall callback, System.String method) [0x00018] in D:\a\BeatSaber-IPA-Reloaded\BeatSaber-IPA-Reloaded\IPA.Loader\Loader\Composite\CompositeBSPlugin.cs:26 
```

**Comment by WentTheFox** [comment]
That mod also will needs an update, however I just tested it and further changes were needed in DiscordCore. After taking care of that, everything does seem to work on my end now. I'm going to get an updated release out within the next 30 minutes from both mods.

**Comment by WentTheFox** [comment]
Please check together:
* https://github.com/DJDavid98/BSDataPuller/releases/tag/v2.1.5
* https://github.com/DJDavid98/DiscordCore/releases/tag/v3.0.3
* https://github.com/DJDavid98/bsrpc/releases/tag/v1.1.3

**Comment by AltEvolutions** [comment]
All looks good on my end, thank you for getting it all fixed so quick!

**Comment by WentTheFox** [comment]
No problem!
